### ISSUE TITLE
Medusa

### ISSUE THREAD

**Issue by Caduceus** [Caduceus/decapitatedSoul#5]
### What is this for:
- [x] This project requires immediate attention.
- [x] This currently exists in server, but needs updated.
- [ ] This project is **not** in development, but we need to implement.
- [ ] Brainstorm Phase.

### Steps to achieve this project

- **Medusa** (Awaiting resolution of issue #1) 
  - Line out gear (multiple vocation use) 
  - Daily chest --omitted
  - Medusa loot (Items need to be edited) 
  - Trinket (trade in Medusa hair) 
    - Strand of Medusa hair (11226)
    - NPC to exchange trinket on turn in of hair 
      - Upgrade trinket for more powerful item

### Expected behavior
Team fight again Medusa & her sisters. 

### Environment
Map is already in place

**Comment by vlad-decap** [comment]
Completed Medusa loot
